include: https://git.sr.ht/~emersion/dalligi/blob/master/templates/multi.yml
alpine:
  extends: .dalligi
archlinux:
  extends: .dalligi
freebsd:
  extends: .dalligi

pages:
  stage: deploy
  dependencies:
    - alpine
  script: [ "true" ]
  artifacts:
    paths:
      - public
  only:
    - master
